import puppeteer from 'puppeteer';

export async function generateInvoicePDF(invoice: any, po: any): Promise<Buffer> {
	const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
	const page = await browser.newPage();

	const html = `
		<!DOCTYPE html>
		<html>
		<head>
			<style>
				body { font-family: Arial, sans-serif; padding: 40px; color: #111; }
				.header { display: flex; justify-content: space-between; margin-bottom: 40px; }
				.company { font-size: 24px; font-weight: bold; color: #2563eb; }
				.invoice-title { font-size: 20px; font-weight: bold; }
				.invoice-number { color: #6b7280; }
				table { width: 100%; border-collapse: collapse; margin: 20px 0; }
				th { background: #f3f4f6; padding: 10px; text-align: left; font-size: 12px; }
				td { padding: 10px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
				.totals { margin-left: auto; width: 280px; }
				.total-row { display: flex; justify-content: space-between; padding: 6px 0; }
				.grand-total { font-weight: bold; font-size: 16px; border-top: 2px solid #111; padding-top: 8px; }
				.status-badge { background: #dcfce7; color: #166534; padding: 4px 12px; border-radius: 20px; font-size: 12px; }
			</style>
		</head>
		<body>
			<div class="header">
				<div>
					<div class="company">VendorBridge</div>
					<div style="color:#6b7280;font-size:13px">Procurement &amp; Vendor Management</div>
				</div>
				<div style="text-align:right">
					<div class="invoice-title">INVOICE</div>
					<div class="invoice-number">${invoice.invoiceNumber}</div>
					<div style="font-size:12px;color:#6b7280;margin-top:4px">
						Date: ${new Date(invoice.createdAt).toLocaleDateString('en-IN')}<br/>
						Due: ${new Date(invoice.dueDate).toLocaleDateString('en-IN')}
					</div>
					<div style="margin-top:8px"><span class="status-badge">${invoice.status}</span></div>
				</div>
			</div>

			<div style="margin-bottom:24px">
				<div style="font-size:12px;color:#6b7280;margin-bottom:4px">BILL TO</div>
				<div style="font-weight:500">${po.quotation?.vendor?.name}</div>
				<div style="font-size:13px;color:#6b7280">${po.quotation?.vendor?.email}</div>
			</div>

			<table>
				<thead>
					<tr>
						<th>Item</th>
						<th>Qty</th>
						<th>Unit Price</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					${(po.quotation?.items ?? [])
						.map(
							(item: any) => `
						<tr>
							<td>${item.rfqItemName}</td>
							<td>${item.quantity}</td>
							<td>₹${Number(item.unitPrice).toLocaleString('en-IN')}</td>
							<td>₹${Number(item.totalPrice).toLocaleString('en-IN')}</td>
						</tr>
					`
						)
						.join('')}
				</tbody>
			</table>

			<div class="totals">
				<div class="total-row"><span>Subtotal</span><span>₹${Number(invoice.subtotal).toLocaleString('en-IN')}</span></div>
				<div class="total-row"><span>GST (${invoice.taxRate}%)</span><span>₹${Number(invoice.taxAmount).toLocaleString('en-IN')}</span></div>
				<div class="total-row grand-total"><span>Grand Total</span><span>₹${Number(invoice.grandTotal).toLocaleString('en-IN')}</span></div>
			</div>

			<div style="margin-top:60px;font-size:12px;color:#9ca3af;text-align:center">
				Generated by VendorBridge ERP · ${new Date().toLocaleString('en-IN')}
			</div>
		</body>
		</html>
	`;

	await page.setContent(html);
	const pdf = await page.pdf({ format: 'A4', printBackground: true });
	await browser.close();
	return Buffer.from(pdf);
}
